// ───────────────────────────────────────────────────────────────
// src/app/store/log.actions.ts
// NgRx actions for writing log entries to Firestore
// ───────────────────────────────────────────────────────────────
import { createAction, props } from '@ngrx/store';
import { LogEntry } from '../services/log.service';

/**
 * addLogStart
 * ------------
 * Dispatched whenever you want to persist a log entry.
 * `entry` omits `id` and `createdAt` because those are
 * generated by Firestore and the service.
 */
export const addLogStart = createAction(
  '[Log] Add Start',
  props<{ entry: Omit<LogEntry, 'id' | 'createdAt'> }>()
);

/**
 * addLogSuccess
 * -------------
 * Emitted by LogEffects when Firestore confirms the write.
 * We don’t carry a payload because usually the UI doesn’t
 * need it, but you can add one if desired.
 */
export const addLogSuccess = createAction('[Log] Add Success');

/**
 * addLogFailure
 * -------------
 * Emitted if Firestore rejects the write (e.g. permission error).
 * Carries the error so you could show a toast or dev console.
 */
export const addLogFailure = createAction(
  '[Log] Add Failure',
  props<{ error: any }>()
);
